package com.jagex;

public enum LocShapes implements Identifiable {
    WALL_STRAIGHT(0, 0),
    WALL_DIAGONAL_CORNER(1, 0),
    WALL_WHOLE_CORNER(2, 0),
    WALL_STRAIGHT_CORNER(3, 0),
    STRAIGHT_INSIDE_WALL_DEC(4, 1),
    STRAIGHT_OUSIDE_WALL_DEC(5, 1),
    DIAGONAL_OUTSIDE_WALL_DEC(6, 1),
    DIAGONAL_INSIDE_WALL_DEC(7, 1),
    DIAGONAL_INWALL_DEC(8, 1),
    WALL_INTERACT(9, 2),
    SCENERY_INTERACT(10, 2),
    GROUND_INTERACT(11, 2),
    STRAIGHT_SLOPE_ROOF(12, 2),
    DIAGONAL_SLOPE_ROOF(13, 2),
    DIAGONAL_SLOPE_CONNECT_ROOF(14, 2),
    STRAIGHT_SLOPE_CORNER_CONNECT_ROOF(15, 2),
    STRAIGHT_SLOPE_CORNER_ROOF(16, 2),
    STRAIGHT_FLAT_ROOF(17, 2),
    STRAIGHT_BOTTOM_EDGE_ROOF(18, 2),
    DIAGONAL_BOTTOM_EDGE_CONNECT_ROOF(19, 2),
    STRAIGHT_BOTTOM_EDGE_CONNECT_ROOF(20, 2),
    STRAIGHT_BOTTOM_EDGE_CONNECT_CORNER_ROOF(21, 2),
    GROUND_DECORATION(22, 3);

    public final int type;
    public final int anInt5494;

    LocShapes(int i_1, int i_2) {
        type = i_1;
        anInt5494 = i_2;
    }

    public static LocShapes[] method262() {
        return new LocShapes[]{STRAIGHT_INSIDE_WALL_DEC, STRAIGHT_SLOPE_ROOF, GROUND_INTERACT, STRAIGHT_SLOPE_CORNER_ROOF, STRAIGHT_BOTTOM_EDGE_ROOF, STRAIGHT_BOTTOM_EDGE_CONNECT_ROOF, WALL_INTERACT, STRAIGHT_OUSIDE_WALL_DEC, STRAIGHT_BOTTOM_EDGE_CONNECT_CORNER_ROOF, DIAGONAL_INSIDE_WALL_DEC, WALL_DIAGONAL_CORNER, WALL_STRAIGHT_CORNER, DIAGONAL_INWALL_DEC, WALL_WHOLE_CORNER, SCENERY_INTERACT, DIAGONAL_BOTTOM_EDGE_CONNECT_ROOF, DIAGONAL_OUTSIDE_WALL_DEC, LocShapes.GROUND_DECORATION, DIAGONAL_SLOPE_ROOF, STRAIGHT_FLAT_ROOF, WALL_STRAIGHT, DIAGONAL_SLOPE_CONNECT_ROOF, STRAIGHT_SLOPE_CORNER_CONNECT_ROOF};
    }

    @Override
    public int getValue() {
        return type;
    }
}
