/* d - Decompiled by JODE
 * Visit http://jode.sourceforge.net/
 */
package jagdx;

public class d {
	public static int a = 0;
	public static int f = 16;
	public static int b = 32;
	public static int p = 64;
	static int i = 1;
	public static int k = 1;
	public static int d = 0;
	public static int u = 2;
	public static int x = 0;
	public static int r = 1;
	public static int q = 2;
	public static int n = 3;
	public static int s = 4;
	public static int z = 5;
	public static int y = 6;
	public static int t = 24;
	public static int h = 26;
	public static int v = 27;
	public static int g = 1;
	public static int e = 2;
	public static int c = 4;
	public static int m = 7;
	public static int w = 10;
	public static int j = 26;
	public static int o = 0;
	public static int l = 1;
	public static int ax = 2;
	public static int aa = 3;
	public static int ak = 16;
	public static int ae = 32;
	public static int ao = 0;
	public static int ad = 1;
	public static int av = 2;
	public static int at = 3;
	public static int ah = 4;
	public static int ai = 256;
	public static int al = 0;
	public static int az = 1;
	public static int as = 1;
	public static int ap = 2;
	public static int af = 512;
	public static int aw = 16;
	public static int ab = 8192;
	public static int aj = 1024;
	public static int ay = 8;
	public static int aq = 7;
	public static int ag = 8;
	public static int an = 9;
	public static int au = 14;
	public static int ar = 15;
	public static int ac = 19;
	public static int am = 20;
	public static int bd = 22;
	public static int bf = 23;
	public static int be = 24;
	public static int by = 25;
	public static int bm = 27;
	public static int bc = 28;
	public static int bx = 34;
	public static int bo = 35;
	public static int bb = 36;
	public static int bl = 37;
	public static int bu = 38;
	public static int bw = 60;
	public static int bk = 137;
	public static int bq = 145;
	public static int bg = 147;
	public static int bs = 154;
	public static int bp = 161;
	public static int bv = 168;
	public static int bh = 174;
	public static int bn = 206;
	public static int bi = 207;
	public static int ba = 208;
	public static int bt = 2;
	public static int bj = 1;
	public static int br = 1;
	public static int bz = 2;
	public static int cm = 3;
	public static int cd = 4;
	public static int cs = 5;
	public static int cx = 6;
	public static int cl = 4;
	public static int cj = 5;
	public static int co = 1;
	public static int cw = 2;
	public static int cv = 5;
	public static int cy = 6;
	public static int cz = 7;
	public static int cg = 1;
	public static int ck = 2;
	public static int cn = 2;
	public static int ch = 2;
	public static int ct = 3;
	public static int cc = 1;
	public static int ca = 2;
	public static int ci = 5;
	public static int ce = 6;
	public static int cb = 9;
	public static int cr = 1;
	public static int cu = 3;
	public static int cp = 1;
	public static int cq = 3;
	public static int cf = 3;
	public static int dh = 1;
	public static int dg = 3;
	public static int dl = 4;

	private d() throws Throwable {
		throw new Error();
	}
}
