/* D3DCAPS - Decompiled by JODE
 * Visit http://jode.sourceforge.net/
 */
package jagdx;

public class D3DCAPS {
	public static final int anInt769 = 1048576;
	public static final int anInt770 = 16777216;
	public static final int anInt771 = 2;
	public static final int anInt772 = 16;
	public static final int anInt773 = 32;
	public static final int anInt774 = 2;
	public static final int anInt775 = 8192;
	public static final int anInt776 = 16384;
	public static final int anInt777 = 65536;
	public static final int anInt778 = 2;
	public static final int anInt779 = 8;
	public static final int anInt780 = 64;
	public static final int anInt781 = 512;
	public static final int anInt782 = 33554432;
	public int DeviceType;
	public int AdapterOrdinal;
	public int Caps;
	public int Caps2;
	public int Caps3;
	public int PresentationIntervals;
	public int CursorCaps;
	public int DevCaps;
	public int PrimitiveMiscCaps;
	public int RasterCaps;
	public int ZCmpCaps;
	public int SrcBlendCaps;
	public int DestBlendCaps;
	public int AlphaCmpCaps;
	public int ShadeCaps;
	public int TextureCaps;
	public int TextureFilterCaps;
	public int CubeTextureFilterCaps;
	public int VolumeTextureFilterCaps;
	public int TextureAddressCaps;
	public int VolumeTextureAddressCaps;
	public int LineCaps;
	public int MaxTextureWidth;
	public int MaxTextureHeight;
	public int MaxVolumeExtent;
	public int MaxTextureRepeat;
	public int MaxTextureAspectRatio;
	public int MaxAnisotropy;
	public float MaxVertexW;
	public float GuardBandLeft;
	public float GuardBandTop;
	public float GuardBandRight;
	public float GuardBandBottom;
	public float ExtentsAdjust;
	public int StencilCaps;
	public int FVFCaps;
	public int TextureOpCaps;
	public int MaxTextureBlendStages;
	public int MaxSimultaneousTextures;
	public int VertexProcessingCaps;
	public int MaxActiveLights;
	public int MaxUserClipPlanes;
	public int MaxVertexBlendMatrices;
	public int MaxVertexBlendMatrixIndex;
	public float MaxPointSize;
	public int MaxPrimitiveCount;
	public int MaxVertexIndex;
	public int MaxStreams;
	public int MaxStreamStride;
	public int VertexShaderVersion;
	public int MaxVertexShaderConst;
	public int PixelShaderVersion;
	public float PixelShader1xMaxValue;
	public D3DVSHADERCAPS2_0 VS20Caps = new D3DVSHADERCAPS2_0();
	public D3DPSHADERCAPS2_0 PS20Caps = new D3DPSHADERCAPS2_0();
	public int DevCaps2;
	public int MasterAdapterOrdinal;
	public int AdapterOrdinalInGroup;
	public int NumberOfAdaptersInGroup;
	public int DeclTypes;
	public int NumSimultaneousRTs;
	public int StretchRectFilterCaps;
	public int VertexTextureFilterCaps;
	public int MaxVShaderInstructionsExecuted;
	public int MaxPShaderInstructionsExecuted;
	public int MaxVertexShader30InstructionSlots;
	public int MaxPixelShader30InstructionSlots;
}
